### ISSUE TITLE
update gradients

### ISSUE THREAD

**Issue by gwynethwoolwine** [gwynethwoolwine/gwynethwoolwine.xyz#1]
using [gradient.style](https://gradient.style/#type=radial&space=oklab&radial_shape=circle&radial_position=%7B%22x%22%3A0%2C%22y%22%3A0%7D&radial_named_position=top+left&radial_size=farthest-corner&stops=%7B%22kind%22%3A%22stop%22%2C%22color%22%3A%22oklch%2880%25+.4+222%29%22%2C%22auto%22%3A%220%22%2C%22position1%22%3A%220%22%2C%22position2%22%3A%220%22%7D&stops=%7B%22kind%22%3A%22hint%22%2C%22auto%22%3A%2250%22%2C%22percentage%22%3A%2250%22%7D&stops=%7B%22kind%22%3A%22stop%22%2C%22color%22%3A%22oklch%2868%25+0.19+19%29%22%2C%22auto%22%3A%22100%22%2C%22position1%22%3A%22100%22%2C%22position2%22%3A%22100%22%7D)

```css
.modern-gradient {
  background-image: 
    radial-gradient(
      farthest-corner circle at 0% 0% in oklab, 
      oklch(80% .4 222) 0%, oklch(68% 0.19 19) 100%
    )
  ;
}

.classic-gradient {
  background-image: 
    radial-gradient(
      farthest-corner circle at 0% 0%, 
      #00dfff 0%, #f75b68 100%
    )
  ;
}
```
